export const PLAYERS = [
    {
        id: "camilo.varon",
        nombre: "Camilo",
        apellido: "Varon",
        edad: 34,
        pais: "Colombia",
        posicion: "Shortstop",
    },
    {
        id: "wladimir.pulido",
        nombre: "Wladimir",
        apellido: "Pulido",
        edad: 25,
        pais: "Venezuela",
        posicion: "Centerfield",
    },
    {
        id: "albert.arias",
        nombre: "Albert",
        apellido: "Arias",
        edad: 30,
        pais: "Dominicana",
        posicion: "shortstop",
    },
    {
        id: "luis.pulido.jr",
        nombre: "Luis",
        apellido: "pulido Jr",
        edad: 34,
        pais: "Venezuela",
        posicion: "3b",
    },
    {
        id: "luis.pulido",   
        nombre: "Luis",
        apellido: "Pulido Sr",
        edad: 50,
        pais: "Venezuela",
        posicion: "Manager",
    },
    {
        id: "felix.bruno",
        nombre: "Felix",
        apellido: "Bruno",
        edad: 38,
        pais: "Dominicana",
        posicion: "Pitcher",
    },
    {
        id: "camilo.varon",
        nombre: "Luis",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Catcher",
    },
    {
        id: "camilo.varon",
        nombre: "Luis",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Catcher",
    },
    {
        id: "camilo.varon",
        nombre: "Luis",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Catcher",
    },
    {
        id: "camilo.varon",
        nombre: "Luis",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Catcher",
    },
]