export const PLAYERS = [
    {
        id: "camilo-varon",
        nombre: "Camilo",
        apellido: "Varon",
        edad: 34,
        pais: "Colombia",
        posicion: "Shortstop",
        equipo: "angeles",
        social:{
            instagram: "https://www.instagram.com/cavb1205/",
            twitter: "https://www.instagram.com/cavb1205/",
            facebook: "https://www.instagram.com/cavb1205/"
        }
    },
    {
        id: "wladimir-pulido",
        nombre: "Wladimir",
        apellido: "Pulido",
        edad: 25,
        pais: "Venezuela",
        posicion: "Centerfield",
        equipo: "angeles",
    },
    {
        id: "albert-arias",
        nombre: "Albert",
        apellido: "Arias",
        edad: 30,
        pais: "Dominicana",
        posicion: "shortstop",
        equipo: "angeles",
    },
    {
        id: "luis-pulido-jr",
        nombre: "Luis",
        apellido: "pulido Jr",
        edad: 34,
        pais: "Venezuela",
        posicion: "3b",
        equipo: "angeles",
    },
    {
        id: "luis-pulido",   
        nombre: "Luis",
        apellido: "Pulido Sr",
        edad: 50,
        pais: "Venezuela",
        posicion: "Manager",
        equipo: "angeles",
    },
    {
        id: "felix-bruno",
        nombre: "Felix",
        apellido: "Bruno",
        edad: 38,
        pais: "Dominicana",
        posicion: "Pitcher",
        equipo: "angeles",
    },
    {
        id: "camilo-varon",
        nombre: "Luis",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Catcher",
        equipo: "angeles",
    },
    {
        id: "camilo-varon",
        nombre: "Jose",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "1b",
        equipo: "barinas",
    },
    {
        id: "camilo-varon",
        nombre: "Pedro",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "2b",
        equipo: "barinas",
    },
    {
        id: "camilo-varon",
        nombre: "Juan",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "3b",
        equipo: "barinas",
    },
    {
        id: "camilo-varon",
        nombre: "Maria",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Shortstop",
        equipo: "barinas",
    },
    {
        id: "camilo-varon",
        nombre: "Ana",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Centerfield",
        equipo: "barinas",
    },
    {
        id: "camilo-varon",
        nombre: "Antonio",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Rightfield",
        equipo: "barinas",
    },
    {
        id: "camilo-varon",
        nombre: "Jose",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Leftfield",
        equipo: "barinas",
    },
    {
        id: "camilo-varon",
        nombre: "Pedro",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Pitcher",
        equipo: "barinas",
    },
    {
        id: "camilo-varon",
        nombre: "Juan",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Catcher",
        equipo: "barinas",
    },
    {
        id: "camilo-varon",
        nombre: "kote",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Catcher",
        equipo: "zorros",
    },
    {
        id: "camilo-varon",
        nombre: "kote",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Catcher",
        equipo: "zorros",
    },
    {
        id: "camilo-varon",
        nombre: "kote",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Catcher",
        equipo: "zorros",
    },
    {
        id: "camilo-varon",
        nombre: "kote",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Catcher",
        equipo: "zorros",
    },
    {
        id: "camilo-varon",
        nombre: "Juan",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Catcher",
        equipo: "zorros",
    },
    {
        id: "camilo-varon",
        nombre: "Juan",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Catcher",
        equipo: "zorros",
    },
    {
        id: "camilo-varon",
        nombre: "Juan",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Catcher",
        equipo: "zorros",
    },
    {
        id: "camilo-varon",
        nombre: "Juan",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Catcher",
        equipo: "zorros",
    },
    {
        id: "camilo-varon",
        nombre: "Juan",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Colombia",
        posicion: "Catcher",
        equipo: "zorros",
    },
    {
        id: "juan-gonzales",
        nombre: "Juan",
        apellido: "Gonzalez",
        edad: 22,
        pais: "Venezuela",
        posicion: "Catcher",
        equipo: "zorros",
    },
    {
        id: "no-retrato",
        nombre: "yeison",
        apellido: "noguera",
        edad: 22,
        pais: "Venezuela",
        posicion: "centerfield",
        equipo: "phillies",
    },
    
]